services:
  #
  # Instagram Tag Media Parser
  #
  instagram_parser:
    class: Mineur\InstagramParser\Instagram
    factory: ['Mineur\InstagramParser\Instagram', createTagParser]
    arguments:
      - '%query_id%'